import { renderToString } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { App } from './App';
import { Briefing } from './routes/Briefing.tsx';
import { Waiting } from './routes/Waiting.tsx';
import { type RoundSpec, ROUNDS, buildPuzzle, sampleFor } from './protocol/rounds.ts';
import type { PlayerView, Role } from './protocol/types.ts';

/**
 * A server render is not a substitute for playing the thing, but it exercises the whole
 * import graph and the first paint, which is where a bad hook order or a circular import
 * shows up. It also proves the app survives an environment with no localStorage, no
 * matchMedia and no EventSource — which is what a locked-down phone browser looks like,
 * and this app has rather more of that machinery than the booth ones do.
 */
describe('App', () => {
  it('renders without a DOM or an event stream', () => {
    const html = renderToString(<App />);

    expect(html).toContain('Telephone');
    expect(html).toContain('Competitive Programming at GT');
  });

  it('renders the briefing screen, samples and all', () => {
    const html = renderToString(<Briefing joinUrl="https://example.test" />);
    expect(html).toContain('Telephone');
    expect(html).toContain('example.test');
    // One sample per round, generated by the same code the rounds use, so a broken
    // generator fails here rather than on a projector in front of the club.
    expect(html.split('<figure').length - 1).toBe(ROUNDS.length);
  });

  /**
   * The game never names its own technique, for the same reason the Stone Game is never
   * called Nim: a name on screen is a search term, and the search hands over the answer.
   */
  it('never names what it is teaching', () => {
    const html = [
      renderToString(<App />),
      renderToString(<Briefing joinUrl="https://example.test" />),
    ].join(' ');

    for (const word of [
      'compress',
      'encoding',
      'entropy',
      'information theory',
      'run-length',
      'delta',
      'chain code',
      'bit packing',
      'Huffman',
    ]) {
      expect(html.toLowerCase(), word).not.toContain(word.toLowerCase());
    }
  });
});

/**
 * Protocol time is the only moment both halves of a team are looking at the same picture,
 * and the whole point of the phase is that they agree how to describe one. A sender
 * describing a shape the receiver has never seen the like of is not agreeing a protocol.
 */
describe('protocol time', () => {
  const mono = ROUNDS.find((r) => r.levels === 1);
  const coloured = ROUNDS.find((r) => r.levels > 1);
  if (mono === undefined || coloured === undefined) throw new Error('missing round');

  const viewFor = (role: Role, phase: 'brief' | 'done', spec: RoundSpec): PlayerView =>
    ({
      kind: role,
      v: 1,
      serverTime: 0,
      team: { id: 't', name: 'SEGFAULT', code: '4821', sender: 'held', receiver: 'held' },
      round: {
        id: spec.id,
        index: spec.index,
        total: ROUNDS.length,
        w: spec.size.w,
        h: spec.size.h,
        levels: spec.levels,
        shapeGiven: spec.shapeGiven,
        lossy: spec.dropRate > 0,
        counts: spec.counts,
        phase,
        phaseEndsAt: null,
        snakeLength: 0,
      },
      shapePath: null,
      sent: [],
      received: [],
      messagesUsed: 0,
      solved: false,
      reveal: null,
      standing: null,
      ...(role === 'sender' ? { target: '' } : { grid: '', gridRev: 0, submittedAt: null }),
    }) as PlayerView;

  const render = (role: Role, phase: 'brief' | 'done' = 'brief', spec = mono): string =>
    renderToString(
      <Waiting
        view={viewFor(role, phase, spec)}
        meeting={{ health: 'live' }}
        role={role}
        msLeft={60_000}
      />,
    );

  // Leaving is for a pair who picked the wrong way round while reading the brief. Once the
  // clock is running it is just a way to abandon your partner, so it is not offered.
  it('offers a way out of the wrong seat, but only before the clock starts', () => {
    expect(render('sender')).toContain('Wrong seat?');
    expect(render('receiver')).toContain('Wrong seat?');
    expect(render('sender', 'done')).not.toContain('Wrong seat?');
  });

  it('shows both players an example, and calls the phase what it is', () => {
    for (const role of ['sender', 'receiver'] as const) {
      const html = render(role);
      expect(html).toContain('Agree on a protocol');
      // The rails are what make an example worth showing: you cannot agree on "row three"
      // without both of you being able to see which row is three.
      expect(html).toContain('An example');
    }
  });

  // Agreeing what to call a shade, off a picture that does not say which shade it is, is
  // the same guessing game the numbers were added to the sender's grid to end.
  it('numbers the colours on the example, for both of them', () => {
    for (const role of ['sender', 'receiver'] as const) {
      const html = render(role, 'brief', coloured);
      expect(html).toMatch(/>[1-9]<\/span>/);
    }
  });

  // `SnakeGrid` draws a div per cell rather than emitting the grid string, so this
  // compares the rendered picture itself between the two roles.
  it('draws the same example for both halves of the team', () => {
    const example = (html: string): string =>
      html.slice(html.indexOf('An example'), html.indexOf('You are both looking at this'));

    const sender = example(render('sender'));
    expect(sender.length).toBeGreaterThan(0);
    expect(sender).toBe(example(render('receiver')));
    // The rails are the point: you cannot agree on "row three" if neither of you can see
    // which row is three.
    expect(sender).toContain(`grid-template-columns:repeat(${mono.size.w}`);
  });

  // If the example ever came from the meeting's seed it would be the answer, handed to the
  // receiver, before the round had started.
  it('is never the picture the round is actually played on', () => {
    for (const round of ROUNDS) {
      for (const seed of ['meeting-a', 'meeting-b', 'deadbeef']) {
        expect(sampleFor(round).grid, round.id).not.toBe(buildPuzzle(round, seed).grid);
      }
    }
  });
});
