import { renderToString } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { App } from './App';
import { Briefing } from './routes/Briefing.tsx';
import { ROUNDS } from './protocol/rounds.ts';

/**
 * A server render is not a substitute for playing the thing, but it exercises the whole
 * import graph and the first paint, which is where a bad hook order or a circular import
 * shows up. It also proves the app survives an environment with no localStorage, no
 * matchMedia and no EventSource — which is what a locked-down phone browser looks like,
 * and this app has rather more of that machinery than the booth ones do.
 */
describe('App', () => {
  it('renders without a DOM or an event stream', () => {
    const html = renderToString(<App />);

    expect(html).toContain('Telephone');
    expect(html).toContain('Competitive Programming at GT');
  });

  it('renders the briefing screen, samples and all', () => {
    const html = renderToString(<Briefing joinUrl="https://example.test" />);
    expect(html).toContain('Telephone');
    expect(html).toContain('example.test');
    // One sample per round, generated by the same code the rounds use, so a broken
    // generator fails here rather than on a projector in front of the club.
    expect(html.split('<figure').length - 1).toBe(ROUNDS.length);
  });

  /**
   * The game never names its own technique, for the same reason the Stone Game is never
   * called Nim: a name on screen is a search term, and the search hands over the answer.
   */
  it('never names what it is teaching', () => {
    const html = [
      renderToString(<App />),
      renderToString(<Briefing joinUrl="https://example.test" />),
    ].join(' ');

    for (const word of [
      'compress',
      'encoding',
      'entropy',
      'information theory',
      'run-length',
      'delta',
      'chain code',
      'bit packing',
      'Huffman',
    ]) {
      expect(html.toLowerCase(), word).not.toContain(word.toLowerCase());
    }
  });
});
