// Regenerates shared/src/components/DiscordQR.tsx.
//
// The QR matrix is baked into a committed component rather than encoded at runtime,
// so the app carries no QR dependency and the booth needs no network. Requires the
// `qrencode` binary (pacman -S qrencode). Run from the repo root:
//
//   node shared/scripts/make-qr.mjs
//
// The Discord glyph is the CC0 mark from simple-icons.

import { execFileSync } from 'node:child_process';
import { writeFile } from 'node:fs/promises';

const INVITE = 'https://discord.gg/5X7UVThEhJ';
const OUT = 'shared/src/components/DiscordQR.tsx';

// Error correction H recovers ~30% of the symbol, which is what lets a logo sit in
// the middle without breaking the scan.
const ascii = execFileSync('qrencode', ['-t', 'ASCII', '-m', '0', '-l', 'H', INVITE], {
  encoding: 'utf8',
});

const rows = ascii
  .split('\n')
  .filter((line) => line.length > 0)
  .map((line) => {
    const cells = [];
    for (let i = 0; i < line.length; i += 2) cells.push(line[i] === '#');
    return cells;
  });

const size = rows.length;
if (rows.some((r) => r.length !== size)) throw new Error('QR matrix is not square');

// Merge each row's dark modules into horizontal runs; a rect per module would be
// several times the path data for an identical result.
const segments = [];
rows.forEach((cells, y) => {
  let x = 0;
  while (x < size) {
    if (!cells[x]) {
      x += 1;
      continue;
    }
    const start = x;
    while (x < size && cells[x]) x += 1;
    segments.push(`M${start} ${y}h${x - start}v1h-${x - start}z`);
  }
});

const discordSvg = await fetch(
  'https://raw.githubusercontent.com/simple-icons/simple-icons/master/icons/discord.svg',
).then((r) => r.text());
const glyph = discordSvg.match(/ d="([^"]+)"/)?.[1];
if (!glyph) throw new Error('could not read the Discord glyph path');

// A 4-module quiet zone is what the spec asks for; 2 is enough in light mode only
// because the plate matches the page, and dark mode has no such luck.
// Logo plate: 9 of 33 modules wide, centred. ~7% of the symbol area, well inside
// what level H tolerates.
const QUIET = 4;
const PLATE = 9;
const GLYPH = 6.4;
const plateXY = (size - PLATE) / 2;
const glyphOffset = plateXY + (PLATE - GLYPH) / 2;
const glyphScale = GLYPH / 24;

const file = `// GENERATED by shared/scripts/make-qr.mjs — edit that script, not this file.
// Encodes ${INVITE} at error-correction level H.

import { cn } from '../cn';

const MODULES =
  '${segments.join('')}';

const GLYPH =
  '${glyph}';

export type DiscordQRProps = {
  className?: string;
};

/**
 * Deliberately not a link. On an unattended booth screen a stray click on a link
 * navigates the game away and a volunteer has to come back and fix it; this is for
 * pointing a phone at, nothing else.
 *
 * The colours are hard-coded rather than themed. Plenty of scanners refuse an
 * inverted (light-on-dark) symbol, so the plate stays light in dark mode too.
 */
export function DiscordQR({ className }: DiscordQRProps) {
  return (
    <svg
      viewBox="-${QUIET} -${QUIET} ${size + QUIET * 2} ${size + QUIET * 2}"
      role="img"
      aria-label="Discord invite QR code for discord.gg/5X7UVThEhJ"
      shapeRendering="crispEdges"
      className={cn('block', className)}
    >
      <rect
        x="-${QUIET}"
        y="-${QUIET}"
        width="${size + QUIET * 2}"
        height="${size + QUIET * 2}"
        fill="#faf9f7"
      />
      <path d={MODULES} fill="#16150f" />
      <rect
        x="${plateXY}"
        y="${plateXY}"
        width="${PLATE}"
        height="${PLATE}"
        rx="2"
        fill="#5865f2"
      />
      <g
        transform="translate(${glyphOffset.toFixed(3)} ${glyphOffset.toFixed(3)}) scale(${glyphScale.toFixed(5)})"
        shapeRendering="geometricPrecision"
      >
        <path d={GLYPH} fill="#ffffff" />
      </g>
    </svg>
  );
}
`;

await writeFile(OUT, file);
console.log(`wrote ${OUT} — ${size}x${size} modules, ${segments.length} runs`);
