import { MicroLabel, useFitScale } from '@cpatgt/shared';
import logoUrl from '@cpatgt/shared/assets/logo.png';
import { SnakeGrid } from '../components/SnakeGrid.tsx';
import { MAX_DIGITS, ROUNDS, buildPuzzle } from '../protocol/rounds.ts';

/**
 * What is on the projector while teams are joining.
 *
 * The samples are generated by the same code that generates the real rounds, from a fixed
 * seed — so what a team plans against is exactly the kind of thing they will get, and
 * there is no separate set of example pictures to fall out of date.
 *
 * Showing every round up front is deliberate. Planning an encoding before any clock
 * starts is the actual skill the evening is about, and it means nobody loses two minutes
 * of a round working out what the round even is.
 *
 * Same vertical budget as the host board — 96 / 888 / 96, every section clipping rather
 * than growing — because a briefing slide that needs scrolling is one the room never
 * finishes reading. The sample grids are sized in pixels rather than by flex, since an
 * `aspect-square` grid inside a flexible column will happily grow past whatever
 * `max-height` you put on its wrapper, which is what made this overflow before.
 */

const W = 1920;
const H = 1080;
const SAMPLE_SEED = 'briefing';
const SAMPLE = 148;

export function Briefing({ joinUrl }: { joinUrl: string }) {
  const scale = useFitScale(W, H);
  const host = joinUrl.replace(/^https?:\/\//, '');

  return (
    <div
      data-theme="light"
      className="flex h-dvh items-center justify-center overflow-hidden bg-ground"
    >
      <div style={{ width: W * scale, height: H * scale }}>
        <div
          style={{ width: W, height: H, transform: `scale(${scale})`, transformOrigin: 'top left' }}
          className="flex flex-col overflow-hidden bg-ground text-ink"
        >
          {/* 96 */}
          <header className="flex h-24 shrink-0 items-center gap-5 border-b border-hairline px-14">
            <img src={logoUrl} alt="" aria-hidden="true" className="size-10" />
            <MicroLabel size="xl" className="text-ink">
              Competitive Programming at GT
            </MicroLabel>
          </header>

          {/* 888 */}
          <main className="grid min-h-0 flex-1 grid-cols-[760px_1160px]">
            <section className="flex min-h-0 flex-col justify-center gap-8 overflow-hidden border-r border-hairline px-14">
              <h1 className="text-[5.5rem] font-semibold leading-none tracking-[-0.03em]">
                Telephone
              </h1>
              <p className="text-[2rem] leading-tight text-ink-muted">
                One of you sees a snake. The other has to draw it. Split up — you only get
                digits.
              </p>

              <div className="flex flex-col gap-3 border-t border-hairline pt-8">
                <MicroLabel size="lg">Join on your phone</MicroLabel>
                <p className="font-mono text-[3.25rem] leading-none tnum">{host}</p>
              </div>

              <ol className="flex flex-col gap-3 text-[1.5rem] leading-snug text-ink-muted">
                <Step n="1" text="One of you taps Start a team." />
                <Step n="2" text="Read the four digits out loud." />
                <Step n="3" text="The other taps Join your partner and types them in." />
                <Step n="4" text="Then go and stand somewhere apart." />
              </ol>
            </section>

            <section className="flex min-h-0 flex-col justify-center gap-9 overflow-hidden px-14">
              <dl className="flex flex-col gap-5">
                <Fact
                  term="Messages"
                  detail={`Digits 0–9, at most ${MAX_DIGITS} of them. Either of you may send; a reply costs one too.`}
                />
                <Fact
                  term="The grid"
                  detail="Rows down from the top, columns across from the left. A cell is row then column."
                />
                <Fact
                  term="The snake"
                  detail="One unbroken line that never touches itself — two cells sit side by side only if they are neighbours along the snake."
                />
                <Fact
                  term="Winning"
                  detail="The drawing is right or it is not. Submit as often as you like. Fewest messages wins."
                />
              </dl>

              <div className="flex flex-col gap-4 border-t border-hairline pt-8">
                <MicroLabel size="lg">The six rounds</MicroLabel>
                <div className="flex gap-5">
                  {ROUNDS.map((spec) => {
                    const { grid } = buildPuzzle(spec, SAMPLE_SEED);
                    return (
                      <figure key={spec.id} className="flex flex-col gap-2">
                        <div style={{ width: SAMPLE }}>
                          <SnakeGrid size={spec.size} grid={grid} levels={spec.levels} />
                        </div>
                        <figcaption className="flex items-baseline justify-between">
                          <MicroLabel>{spec.index}</MicroLabel>
                          <span className="font-mono text-[1rem] tnum text-ink-faint">
                            {spec.size.w}×{spec.size.h}
                          </span>
                        </figcaption>
                      </figure>
                    );
                  })}
                </div>
              </div>
            </section>
          </main>

          {/* 96 */}
          <footer className="flex h-24 shrink-0 items-center justify-between border-t border-hairline px-14 text-[1.375rem] text-ink-faint">
            <span>Round 0 is a warm-up and does not count.</span>
            <span>Nothing is dropped until the last round.</span>
          </footer>
        </div>
      </div>
    </div>
  );
}

function Step({ n, text }: { n: string; text: string }) {
  return (
    <li className="flex gap-4">
      <span className="font-mono tnum text-ink-faint">{n}</span>
      <span>{text}</span>
    </li>
  );
}

function Fact({ term, detail }: { term: string; detail: string }) {
  return (
    <div className="flex flex-col gap-1.5">
      <dt>
        <MicroLabel size="lg" className="text-ink">
          {term}
        </MicroLabel>
      </dt>
      <dd className="text-[1.625rem] leading-snug text-ink-muted">{detail}</dd>
    </div>
  );
}
